export const ORDER_ACCEPT_REQUEST: 'ORDER_ACCEPT_REQUEST' = 'ORDER_ACCEPT_REQUEST';
export const ORDER_ACCEPT_SUCCESS: 'ORDER_ACCEPT_SUCCESS' = 'ORDER_ACCEPT_SUCCESS';
export const ORDER_ACCEPT_FAILED: 'ORDER_ACCEPT_FAILED' = 'ORDER_ACCEPT_FAILED';
export const CLOSE_ORDER_ACCEPT: 'CLOSE_ORDER_ACCEPT' = 'CLOSE_ORDER_ACCEPT';